### ISSUE TITLE
TiltAngle integration

### ISSUE THREAD

**Issue by gamade** [Foxi352/homebridge-smarthomeng#3]
Add CurrentTiltAngle and TargetTiltAngle Attributes for use of WindowCovering with "Raffstoren".

**Comment by Foxi352** [comment]
Do you still use this plugin ? 
I am completely rewriting it from scratch right not (see progress in v2-dev branch). WindowConvering have already been added but again without the TiltAngle. I don't have such gear to test it. If you are still using it i would add that support in the first v2.0.0 release and count on you to test it.

**Comment by gamade** [comment]
Yes, I do. But I did not update smarthome / smartvisu for the last month, because at the moment everything works fine. So, If you have a new Version release, please give me a hint.

**Comment by Foxi352** [comment]
A beta v2.0.1 has been pushed to npmjs.

You should be able to install it with ```sudo npm install -g homebridge-smarthomeng@beta```

You have to adapt your config.json before trying it. You'll find all needed documentation in the README here in the repo.

**Comment by Foxi352** [comment]
Included and should be working since v2.0.1
