### ISSUE TITLE
Outdated states/values after restarting the Home App

### ISSUE THREAD

**Issue by Sebastian-Maier** [Foxi352/homebridge-smarthomeng#8]
When I change the state of arbitrary devices (e.g., turning lights on/off) via the Home App, I will observe outdated values after closing the Home App and reopening it. In contrast, updates that are issued via SmarthomeNG/KNX (e.g, turning lights on/off manually) are always visible (and preserved even after restarting the Home App).

The updates issued by Homebridge to SmarthomeNG/KNX are for some reason not cached (i.e., do not result in `lastValue` being updated directly or indirectly). Is this a bug or a misconfiguration on my side? Should the updated value (sent to SmarthomeNG/KNX) finally result in an indirect update being delivered from SmarthomeNG/KNX back to the plugin after a successful update of the value (that in turn also updates `lastValue`)?

As a fix, I added a mechanism to update the lastValue stored with each update issued by Homebridge (assuming the new value is always successfully updated via SmarthomeNG/KNX).
In case this is an actual bug, the corresponding changes will be available shortly in the form of a pull request.

**Comment by Foxi352** [comment]
Thank you for all your efforts. Will analyse this one a.s.a.p. and check on my own installation.

**Comment by Sebastian-Maier** [comment]
Thank you for the cool plugin and your prompt response. :-)
